### PR TITLE
Add optional keyExchangeGroup string

### LINKED ISSUE #17: Elliptical curve
As far as I see the proposal does not include an API for showing the elliptical curve used in ECDHE or ECDSA.

Ref: https://github.com/sibiantony/ssleuth/issues/45

### PR DESCRIPTION
**Pull request by rolandshoemaker**
Fixes #17.

### CODE REVIEW

**Comment by rugk** [comment]
Why only optional?

**Comment by rolandshoemaker** [comment]
Various key exchange methods, i.e. static RSA exchanges, don't have group IDs.

**Comment by rugk** [comment]
Ah, that is another "optional" than I thought of. Maybe clarify it that if the data is available it should be presented and not the way I thought of optional: "Yeah, browser vendors can show the data here or not, we don't care".

**Comment by rolandshoemaker** [comment]
The whole proposal is optional to browsers, they will implement of it what they want. The term 'optional' is used throughout to imply 'should be provided if available', perhaps that should be clarified.

**Pull request merged**
